MACH: Add an empty stub for function msm_iommu_get_ctx
Fixs: error: undefined reference to 'msm_iommu_get_ctx'

When IOMMU feature is turned off an empty stub for function
msm_iommu_get_ctx is required so that other modules using
this function may compile.

Signed-off-by: Shubhraprakash Das <sadas@codeaurora.org>