MSM: Change clock to resemble 2.6.38
This commit cause the errors below, they will be fixed.

Errors:
LD      vmlinux.o
/home/croniccorey/Dev/Toolchains/linaro-toolchain-eabi-4.8/bin/arm-eabi-ld: error: drivers/built-in.o: multiple definition of 'clk_get'
/home/croniccorey/Dev/Toolchains/linaro-toolchain-eabi-4.8/bin/arm-eabi-ld: arch/arm/mach-msm/built-in.o: previous definition here
/home/croniccorey/Dev/Toolchains/linaro-toolchain-eabi-4.8/bin/arm-eabi-ld: error: drivers/built-in.o: multiple definition of 'clk_put'
/home/croniccorey/Dev/Toolchains/linaro-toolchain-eabi-4.8/bin/arm-eabi-ld: arch/arm/mach-msm/built-in.o: previous definition here
make: *** [vmlinux.o] Error 1