MSM: Add missing include in board-bravo.h
This commit adds #include <asm/system_info.h> to board-bravo.h

Fixs the errors below:
note: in expansion of macro 'is_cdma_version'
error: 'system_rev' undeclared (first use in this function)